---
title: "Exemplos de aplicativos da web em Shiny"
lang: pt
format: html
---

Cada exemplo abaixo traz um arquivo em R contendo os códigos do aplicativo e um link para o aplicativo em funcionamento. 

Você pode baixar o arquivo R e executar o app no RStudio. 

Você também pode publicar gratuitamente o app no site do RStudio, que se chama `shinyapps`. Para isso, após visualizar o app (usando o botão `Run App`), clique no botão azul chamado `Publish the application` e faça sua inscrição no site para publicar gratuitamente.

<!--
- **Exemplo 1:** `Hello world`. O aplicativo apenas mostra a frase na tela.

[App1 online](https://mauricio-camargo.shinyapps.io/ex_shiny1)  
[Códigos do App1](ex_shiny1/app1.R)  
-->

- **Exemplo 2:** Exemplo simples de histograma que pode ter o número de classes modificado dinamicamente.

[App2 online](https://mauricio-camargo.shinyapps.io/ex_shiny2)  
[Códigos do App2](ex_shiny2/app2.R)  

- **Exemplo 3:** Demonstra o efeito na curva normal da mudança da média e do desvio padrão, para números gerados aleatoriamente.

[App3 online](https://mauricio-camargo.shinyapps.io/ex_shiny3)  
[Códigos do App3](ex_shiny3/app3.R)  

- **Exemplo 4:** Variação do efeito da inclinação, do intercepto e do ruído sobre um ajuste por regressão linear.

[App4 online](https://mauricio-camargo.shinyapps.io/ex_shiny4)  
[Códigos do App4](ex_shiny4/app4.R)  

- **Exemplo 5:** Demonstra o efeito de um outlier na regressão.

[App5 online](https://mauricio-camargo.shinyapps.io/ex_shiny5)  
[Códigos do App5](ex_shiny5/app5.R)  

- **Exemplo 6:** Demonstração do teorema do limite central.

[App6 online](https://mauricio-camargo.shinyapps.io/app61)  
[Códigos do App6](ex_shiny6/app.R)  
