---
title: "Tarefa 3"
format: html
lang: pt
---

---

:::{.callout-warning}
Esta tarefa será feita em sala de aula.
:::

---

<br>
Cada aluno deve escolher um trabalho científico da sua preferência e salvar no seu computador, em pdf.  
<br>
Sua tarefa será divulgar este trabalho científico no seu site, criando uma nova página contendo a descrição do trabalho e um link para uma nova apresentação em revealjs do trabalho.  
<br>
Todo o conteúdo escrito pode ser fake, contendo apenas algumas linhas em cada tópico, sem se preocupar com o sentido do texto. Contudo, o formato e a qualidade gráfica são muito importantes.

Os passos da tarefa são os seguintes:

- Crie um novo documento em Quarto html e salve como `tarefa3.qmd`
- Dê um Commit seguido de um Push para testar o `git`.
- Crie um link na página principal do seu site para a página `tarefa3.html`.
- Coloque conteúdo na nova página (`tarefa3.html`) apresentando o trabalho científico. O conteúdo pode ser muito simplificado.
- Crie uma apresentação em `revealjs` com pelo menos três slides e duas figuras copiadas do trabalho. O arquivo desta apresentação deverá se chamar `apres_tar3.qmd`.
- Crie um link na sua nova página para a apresentação `revealjs`.


